'use strict';
const $=id=>document.getElementById(id),L=Layout,token=document.querySelector('meta[name="app-token"]').content,hosted=token!=='__TOKEN__',fields=[...document.querySelectorAll('[data-field]')];
let project=L.normalize(L.defaults),scene=L.validate(project),lastValid=L.clone(project),history=[],future=[],recent=[],selected=null,selection=new Set(),layoutMode=false,valid=true,ready=false,dirty=false,saveTimer=null,inputTimer=null,toastTimer=null,saveChain=Promise.resolve();
const view={scale:1,x:0,y:0,w:0,h:0,fitted:true},canvas=$('canvas'),ctx=canvas.getContext('2d');
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function fill(){fillWorkspaceControls();for(const e of fields){if(e.type==='checkbox')e.checked=project[e.id];else e.value=['row_groups','col_groups'].includes(e.id)?L.compact(L.list(project[e.id])):project[e.id];}try{const c=L.list(project.col_groups),r=L.list(project.row_groups);$('totalWide').value=c.reduce((a,b)=>a+b,0);$('totalHigh').value=r.reduce((a,b)=>a+b,0);$('sectionCount').value=c.length;$('bandCount').value=r.length;}catch(_){}builderSummary();canvasControls();$('title').textContent=project.projectName;}
function read(){const o=L.clone(project);readWorkspaceControls(o);for(const e of fields)o[e.id]=e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value;try{o.modules_wide=L.list(o.col_groups).reduce((a,b)=>a+b,0);}catch(_){}return o;}
function mismatch(o){let sum;try{sum=L.list(o.col_groups).reduce((a,b)=>a+b,0)}catch(_){}const different=sum!==undefined&&Number(o.modules_wide)!==sum;$('mismatch').hidden=!different;$('mismatchText').textContent=different?`Requested width: ${o.modules_wide}. Section total: ${sum}.`:'';}
function setError(message){valid=false;$('error').textContent=message;$('invalidOverlay').hidden=false;for(const id of ['xlsx','svg','png','csv','sectionCsv','pdf','pdfOverview','saveProject'])$(id).disabled=true;$('undo').disabled=false;$('saveState').textContent='Invalid settings — changes not saved';}
function refresh(){mismatch(project);try{const previousScene=scene,previousSelection=selected?{...selected}:null;const selectionKey=selected&&selected.c<scene.cols&&selected.r<scene.rows?L.info(scene,selected.c,selected.r).key:null;scene=L.validate(project);project=scene.o;selection=new Set([...selection].filter(key=>{try{L.locate(scene,key);return true;}catch(_){return false;}}));if(selectionKey){try{selected=L.locate(scene,selectionKey);}catch(_){selected=null;selection.clear();}}if(selected&&previousSelection&&!view.fitted&&(selected.c!==previousSelection.c||selected.r!==previousSelection.r||scene.o.module_width!==previousScene.o.module_width||scene.o.module_height!==previousScene.o.module_height)){view.x=view.w/2-(activeItem().x+(selected.c+.5)*scene.o.module_width)*view.scale;view.y=view.h/2-(activeItem().y+(selected.r+.5)*scene.o.module_height)*view.scale;}if(!valid)$('saveState').textContent='Settings valid';valid=true;$('error').textContent='';$('invalidOverlay').hidden=true;for(const id of ['xlsx','svg','png','csv','sectionCsv','pdf','pdfOverview','saveProject'])$(id).disabled=false;summary();inspect();render();return true;}catch(e){setError(e.message);return false;}}
function remember(){history.push(L.clone(lastValid));if(history.length>60)history.shift();future=[];}
function commit(o,fit=false,record=true){project=o;if(!refresh())return false;if(JSON.stringify(project)!==JSON.stringify(lastValid)){if(record)remember();lastValid=L.clone(project);dirty=true;scheduleSave();}fill();buttons();if(fit||view.fitted)fitAll();return true;}
function inputChanged(){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{commit(read());},250);}
function flushInput(){clearTimeout(inputTimer);return commit(read());}
function mutate(fn,fit=false){if(!flushInput())return;const o=L.clone(project);try{fn(o);commit(o,fit);}catch(e){toast(e.message);}}
function buttons(){$('undo').disabled=valid&&!history.length;$('redo').disabled=!future.length;}
function undo(){clearTimeout(inputTimer);if(!valid){project=L.clone(lastValid);fill();refresh();buttons();return;}if(!history.length)return;future.push(L.clone(project));project=history.pop();lastValid=L.clone(project);selected=null;selection.clear();fill();refresh();buttons();dirty=true;scheduleSave();}
function redo(){if(!future.length)return;history.push(L.clone(lastValid));project=future.pop();lastValid=L.clone(project);selected=null;selection.clear();fill();refresh();buttons();dirty=true;scheduleSave();}
function summary(){syncEffects();settingsSummary();const s=scene,o=s.o,count=s.cols*s.rows;styleControls();$('title').textContent=o.projectName;$('total').textContent=`${s.cols} × ${s.rows} = ${count.toLocaleString()} modules · ${L.isCabinet(s)?s.cg.length+' × '+s.rg.length+' cabinets':s.cg.length+' horizontal sections'}`;const bounds=L.canvasBounds(s);$('footerTotal').textContent=`${bounds.items.length} layout(s) · ${bounds.W.toLocaleString()} × ${bounds.H.toLocaleString()} px canvas`;$('orientation').textContent=`${o.horizontal_view} · ${o.vertical_order} · ${L.isCabinet(s)?L.cabinetId(s,0,0):'A1'} ↦ ${o.vertical_order==='Top to Bottom'?'top':'bottom'}-${o.horizontal_view==='Rear'?'left':'right'}`;
 try{const p=LayoutPDF.plan(exportScene(),true);$('printSummary').textContent=`${p.pages.length} pages (${o.paper}, ${o.landscape?'landscape':'portrait'}) · detail label size ${p.minFont.toFixed(1)} pt${p.minFont<6?' · Small labels':''}`;}catch(e){$('printSummary').textContent=e.message;}
 const f=L.isCabinet(s)?L.cabinetLabels(s).reduce((min,t)=>Math.min(min,t.fs),Infinity):L.typography(s).fs;$('exportNote').textContent=f<6?'Labels are retained in every export, but this drawing size makes them tiny. Increase drawing size for readable PNG labels.':'SVG, PNG and PDF use the same module geometry and Courier label sizing.';
}
function fitAll(){if(!valid)return;const b=L.canvasBounds(scene);view.fitted=true;view.scale=Math.max(.0001,Math.min(24,(view.w-64)/b.W,(view.h-80)/b.H));view.x=(view.w-b.W*view.scale)/2-b.minX*view.scale;view.y=(view.h-b.H*view.scale)/2-b.minY*view.scale;render();}
function zoomAt(f,x=view.w/2,y=view.h/2){view.fitted=false;const old=view.scale;view.scale=Math.max(.0001,Math.min(24,old*f));view.x=x-(x-view.x)*view.scale/old;view.y=y-(y-view.y)*view.scale/old;render();}
function resize(){const r=$('viewport').getBoundingClientRect(),first=!view.w,oldW=view.w,oldH=view.h;view.w=r.width-2;view.h=r.height-2;view.x+=(view.w-oldW)/2;view.y+=(view.h-oldH)/2;const dpr=window.devicePixelRatio||1;canvas.width=Math.round(view.w*dpr);canvas.height=Math.round(view.h*dpr);if(first||view.fitted)fitAll();else render();}
function render(){if(!scene||!view.w)return;const dpr=window.devicePixelRatio||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,view.w,view.h);ctx.fillStyle='#0a1118';ctx.fillRect(0,0,view.w,view.h);drawCanvasGrid();ctx.save();ctx.translate(view.x,view.y);ctx.scale(view.scale,view.scale);for(const item of L.canvasScenes(scene)){ctx.save();ctx.translate(item.x,item.y);drawLayout(item);ctx.restore();if(layoutMode){ctx.strokeStyle=item.id===project.workspace.activeId?'#82e1bf':'#64748b';ctx.lineWidth=2/view.scale;ctx.strokeRect(item.x,item.y,item.scene.W,item.scene.H);ctx.font=`bold ${12/view.scale}px Arial`;ctx.fillStyle='#E2E8F0';ctx.textAlign='left';ctx.fillText(item.name,item.x,item.y-24/view.scale);ctx.font=`${11/view.scale}px Arial`;ctx.fillText(`X: ${item.x}   Y: ${item.y}`,item.x,item.y-8/view.scale);}}ctx.restore();refreshEffectsFrame();$('zoom').textContent=(view.scale*100).toFixed(view.scale<.1?1:0)+'%';$('scaleHint').textContent=layoutMode?'Drag a layout to move it · Drag empty space to pan':L.isCabinet(scene)?'Click a module to edit its labels':'Click a module · Ctrl-click to select more';}
function drawLayout(item){const s=item.scene,o=s.o,mw=o.module_width,mh=o.module_height,k=view.scale;ctx.fillStyle='white';ctx.fillRect(0,0,s.W,s.H);
 const left=Math.max(0,Math.floor((-view.x/k-item.x)/mw)),right=Math.min(s.cols,Math.ceil(((view.w-view.x)/k-item.x)/mw)),top=Math.max(0,Math.floor((-view.y/k-item.y)/mh)),bottom=Math.min(s.rows,Math.ceil(((view.h-view.y)/k-item.y)/mh));
 const rs=L.rects(s);for(const q of rs){if(q.x+q.w<left||q.x>right||q.y+q.h<top||q.y>bottom)continue;ctx.fillStyle=q.fill;ctx.fillRect(q.x*mw,q.y*mh,q.w*mw,q.h*mh);}
 for(const q of L.highlights(s)){ctx.fillStyle=q.fill;ctx.fillRect(q.x*mw,q.y*mh,mw,mh);}
 ctx.strokeStyle=L.palette(s).grid;L.grid(s,(x1,y1,x2,y2,width)=>{if(!width)return;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();});
 const {fs,off}=L.typography(s),labels=!L.isCabinet(s)&&!L.isTest(s)&&o.show_labels&&fs*k>=5;ctx.fillStyle=o.text_color;ctx.font=`bold ${fs}px "Courier New",monospace`;ctx.textAlign='center';ctx.textBaseline='alphabetic';
 for(let r=top;r<bottom;r++)for(let c=left;c<right;c++){const i=L.info(s,c,r),cx=(c+.5)*mw,cy=(r+.5)*mh;if(labels){const f=L.moduleFont(s,i);ctx.font=`bold ${f}px "Courier New",monospace`;ctx.fillText(L.displayLabel(s,i),cx,cy-off+f*.3);ctx.fillText(L.moduleText(s,i),cx,cy+off+f*.3);}const status=o.module_status[i.key];if(status&&status!=='planned'&&Math.min(mw,mh)*k>8){ctx.save();ctx.fillStyle={installed:'#0284c7',tested:'#059669',replace:'#dc2626'}[status];const b=Math.min(mw,mh)*.14;ctx.fillRect((c+1)*mw-b-2,r*mh+2,b,b);ctx.restore();}}
 if(!L.isCabinet(s)&&!L.isTest(s)&&o.show_headings)for(const q of rs){if(q.x+q.w<left||q.x>right||q.y+q.h<top||q.y>bottom)continue;const f=labels?Math.min(Math.min(mw,mh)*.15,q.w*mw/(q.displayLabel.length*.6+1.4)):Math.min(11/k,q.w*mw/(q.displayLabel.length*.6+1.4),q.h*mh*.3);if(f*k<7)continue;const pad=Math.min(mw,mh)*.02,w=(q.displayLabel.length*.6+1)*f,x=labels?q.x*mw+pad:(q.x+q.w/2)*mw-w/2,y=labels?q.y*mh+pad:(q.y+q.h/2)*mh-f*.65;ctx.fillStyle='white';ctx.fillRect(x,y,w,f*1.3);ctx.fillStyle='#111827';ctx.font=`bold ${f}px "Courier New",monospace`;ctx.textAlign='left';ctx.fillText(q.displayLabel,x+f*.4,y+f);}
 if(L.isCabinet(s)&&o.show_cabinet_labels){ctx.fillStyle=L.palette(s).text;ctx.textAlign='center';for(const t of L.cabinetLabels(s)){if(t.fs*k<3)continue;ctx.font=`bold ${t.fs}px "Courier New",monospace`;ctx.strokeStyle='#263238';ctx.lineWidth=t.fs*.07;ctx.lineJoin='round';ctx.strokeText(t.text,t.x,t.y+t.fs*.3);ctx.fillText(t.text,t.x,t.y+t.fs*.3);}}
 if(L.isCabinet(s)){ctx.textAlign='center';for(const t of L.moduleLabelPositions(s)){ctx.font=`bold ${t.fs}px "Courier New",monospace`;ctx.fillStyle=L.palette(s).text;ctx.strokeStyle='#263238';ctx.lineWidth=t.fs*.06;ctx.strokeText(t.text,t.x,t.y);ctx.fillText(t.text,t.x,t.y);}}
 if(L.isTest(s)){for(const shape of L.testGeometry(s,item.name)){ctx.fillStyle=shape.color;ctx.strokeStyle=shape.color;if(shape.type==='line'){ctx.lineWidth=shape.width;ctx.beginPath();ctx.moveTo(shape.x1,shape.y1);ctx.lineTo(shape.x2,shape.y2);ctx.stroke();}else if(shape.type==='rect')ctx.fillRect(shape.x,shape.y,shape.w,shape.h);else{ctx.font=`bold ${shape.fs}px "Courier New",monospace`;ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.fillText(shape.text,shape.x,shape.y);}}}
 if(item.id===project.workspace.activeId&&!layoutMode){for(const key of selection){const q=L.locate(s,key);ctx.strokeStyle='#0284ff';ctx.lineWidth=2/k;ctx.strokeRect(q.c*mw,q.r*mh,mw,mh);}if(selected){ctx.strokeStyle='#0284ff';ctx.lineWidth=4/k;ctx.strokeRect(selected.c*mw,selected.r*mh,mw,mh);}
}
}
function position(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
let drag=null;
function hitLayout(p){const x=(p.x-view.x)/view.scale,y=(p.y-view.y)/view.scale;return L.canvasScenes(scene).reverse().find(i=>x>=i.x&&y>=i.y&&x<i.x+i.scene.W&&y<i.y+i.scene.H);}
const touches=new Map();let pinch=null;
canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;touches.set(e.pointerId,position(e));if(touches.size>=2){if(drag?.id&&drag.moved)commit(L.clone(project));drag=null;const [a,b]=[...touches.values()];const mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};pinch={distance:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),scale:view.scale,wx:(mid.x-view.x)/view.scale,wy:(mid.y-view.y)/view.scale};canvas.setPointerCapture(e.pointerId);e.stopImmediatePropagation();}},true);
canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,position(e));if(!pinch)return;e.stopImmediatePropagation();if(touches.size<2)return;const [a,b]=[...touches.values()];view.scale=Math.max(.0001,Math.min(24,pinch.scale*Math.hypot(b.x-a.x,b.y-a.y)/pinch.distance));view.x=(a.x+b.x)/2-pinch.wx*view.scale;view.y=(a.y+b.y)/2-pinch.wy*view.scale;view.fitted=false;render();},true);
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{touches.delete(e.pointerId);if(pinch){e.stopImmediatePropagation();drag=null;if(!touches.size)pinch=null;}},true);
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||!valid)return;if(!flushInput())return;const p=position(e),hit=hitLayout(p);if(layoutMode&&hit)activate(hit.id);const item=layoutMode&&hit?activeItem():null;drag={...p,px:view.x,py:view.y,moved:false,id:item?.id,ox:item?.x,oy:item?.y};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=position(e),dx=p.x-drag.x,dy=p.y-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(!drag.moved)return;view.fitted=false;if(drag.id){const item=activeItem();const point=L.Effects.snapLayout({x:drag.ox+dx/view.scale,y:drag.oy+dy/view.scale},item.id,L.canvasScenes(scene),project.workspace.grid,10/view.scale);item.x=point.x;item.y=point.y;$('layoutX').value=item.x;$('layoutY').value=item.y;}else{view.x=drag.px+dx;view.y=drag.py+dy;}render();});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const was=drag;drag=null;if(was.id&&was.moved){commit(L.clone(project));return;}if(was.moved||!valid)return;const p=position(e),hit=hitLayout(p);if(!hit){selected=null;selection.clear();inspect();render();return;}activate(hit.id);if(layoutMode){$('viewport').focus({preventScroll:true});return;}const c=Math.floor(((p.x-view.x)/view.scale-hit.x)/scene.o.module_width),r=Math.floor(((p.y-view.y)/view.scale-hit.y)/scene.o.module_height);selectModule({c,r},e.ctrlKey||e.metaKey,true);});
canvas.addEventListener('pointercancel',()=>{if(drag?.id){project=L.clone(lastValid);refresh();fill();}drag=null;});
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=position(e);zoomAt(Math.exp(-e.deltaY*.0015),p.x,p.y);},{passive:false});
function inspect(){if(!selected||selected.c>=scene.cols||selected.r>=scene.rows){selected=null;selection.clear();$('selectionControls').hidden=true;$('selectedTitle').textContent='No module selected';$('selectedDetails').textContent='';return;}const i=L.info(scene,selected.c,selected.r),o=scene.o;labelControls(i);$('selectionControls').hidden=false;$('selectedTitle').textContent=(selection.size>1?selection.size+' modules selected · Active: ':'')+L.displayLabel(scene,i)+' / '+i.lc+':'+i.lr;$('selectedDetails').textContent=`${activeItem().name} · Address ${L.displayKey(scene,i)} · Display column ${selected.c+1}, row ${selected.r+1} · ${L.isCabinet(scene)?'cabinet':'section'} ${scene.cg[i.sx]} × ${scene.rg[i.sy]} modules`;$('selectedWidth').value=scene.cg[i.sx];$('selectedHeight').value=scene.rg[i.sy];$('selectedColor').value=o.section_colors[i.label]||o.section_colors[i.letter]||(i.li%2?o.color2:o.color1);$('status').value=o.module_status[i.key]||'planned';$('moduleColor').value=o.module_colors[i.key]||'#FFFF00';$('removeModuleHighlight').disabled=![...selection].some(key=>o.module_colors[key]);for(const id of ['resizeSection','setSectionColor','setLetterColor','clearSectionColor'])$(id).disabled=selection.size>1||(L.isCabinet(scene)&&id!=='resizeSection');$('highlightModule').textContent=selection.size>1?'Highlight selected':'Highlight module';$('selectedDetails').textContent+=selection.size>1?' · '+selection.size+' selected':'';}
function selectedInfo(){if(!selected)throw Error('Select a module first.');return L.info(scene,selected.c,selected.r);}
async function api(path,body){const opts={headers:{'X-Layout-Token':token}};if(body!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body);}const r=await fetch(path,opts);if(!r.ok)throw Error(await r.text());return r.json();}
function state(){return {working:L.clone(lastValid),recent:L.clone(recent),updatedAt:new Date().toISOString()};}
function persist(){if(!ready||!valid)return saveChain;const payload=state();saveChain=saveChain.catch(()=>{}).then(async()=>{try{if(hosted)await api('/api/state',payload);else localStorage.setItem('led-layout-mobile-v1',JSON.stringify(payload));$('saveState').textContent='Autosaved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch(e){$('saveState').textContent='Autosave failed — use Save Project';toast('Could not autosave: '+e.message);throw e;}});return saveChain;}
function scheduleSave(){if(!ready)return;$('saveState').textContent='Saving changes…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist().catch(()=>{}),650);}
function updateRecent(){const sel=$('recent');sel.replaceChildren(new Option('Choose a project…',''));recent.forEach((r,i)=>sel.add(new Option(r.project.projectName+' · Rev '+r.project.revision,String(i))));}
function addRecent(o){recent=recent.filter(r=>r.project.projectName!==o.projectName);recent.unshift({project:L.clone(o),savedAt:new Date().toISOString()});recent=recent.slice(0,5);updateRecent();}
async function open(o,recovered=false){if(!recovered&&valid)addRecent(lastValid);const next=L.normalize(o);project=next;lastValid=L.clone(next);history=[];future=[];selected=null;selection.clear();fill();refresh();fitAll();buttons();dirty=false;if(!recovered){addRecent(project);scheduleSave();}}
function filename(ext){return (project.projectName.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'')||'LED_Layout')+'_'+(ext==='json'?'Project':$('exportScope').value==='active'?'ActiveLayout':'Canvas')+'_Rev'+project.revision.replace(/[^a-zA-Z0-9_-]/g,'_')+'.'+ext;}
function download(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);}
async function saveProject(){if(!flushInput())return;addRecent(project);const payload=L.clone(project);let disk=false;try{if(hosted){const result=await api('/api/save',payload);disk=true;toast('Saved to Projects/'+result.file);}await persist();dirty=false;}catch(e){toast('Disk save failed. Downloading a JSON backup: '+e.message);}download(filename('json'),new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));if(!disk)toast('Project JSON downloaded. Keep it with your project files.');}
async function exportRun(id,fn){if(!flushInput())return;const b=$(id);b.disabled=true;b.classList.add('busy');$('exportNote').textContent='Preparing export…';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));try{await fn();toast('Export ready — check your browser downloads.');}catch(e){toast('Export failed: '+e.message);}finally{b.disabled=false;b.classList.remove('busy');summary();}}
async function png(){const s=exportScene(),b=L.canvasBounds(s);const factor=Math.min(1,4096/b.W,4096/b.H,Math.sqrt(12000000/(b.W*b.H)));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.W*factor));c.height=Math.max(1,Math.round(b.H*factor));const cx=c.getContext('2d');if(!cx)throw Error('Canvas could not be allocated.');const url=URL.createObjectURL(new Blob([L.svg(s)],{type:'image/svg+xml'}));try{const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=()=>rej(Error('Could not render image.'));img.src=url;});cx.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(res=>c.toBlob(res,'image/png'));if(!blob)throw Error('PNG memory limit reached. Try SVG.');download(filename('png'),blob);}finally{URL.revokeObjectURL(url);c.width=c.height=1;}}
fields.forEach(e=>{e.addEventListener('input',inputChanged);e.addEventListener('change',()=>{clearTimeout(inputTimer);commit(read());});});
$('resizeSection').onclick=()=>{const w=Number($('selectedWidth').value),h=Number($('selectedHeight').value);mutate(o=>{const i=selectedInfo(),cg=L.list(o.col_groups),rg=L.list(o.row_groups);cg[i.sx]=w;rg[i.sy]=h;o.col_groups=cg.join(',');o.row_groups=rg.join(',');o.modules_wide=cg.reduce((a,b)=>a+b,0);},true);};
$('setSectionColor').onclick=()=>{const color=$('selectedColor').value;mutate(o=>{o.section_colors[selectedInfo().label]=color;});};
$('setLetterColor').onclick=()=>{const color=$('selectedColor').value;mutate(o=>{const i=selectedInfo();o.section_colors[i.letter]=color;for(const label of Object.keys(o.section_colors))if(label.match(/^[A-Z]+(?=\d)/)?.[0]===i.letter)delete o.section_colors[label];});};
$('clearSectionColor').onclick=()=>mutate(o=>{const i=selectedInfo();delete o.section_colors[i.label];delete o.section_colors[i.letter];});
$('highlightModule').onclick=()=>{const color=$('moduleColor').value;mutate(o=>{for(const key of selection)o.module_colors[key]=color;});};
$('removeModuleHighlight').onclick=()=>mutate(o=>{for(const key of selection)delete o.module_colors[key];});
$('status').onchange=()=>{const status=$('status').value;mutate(o=>{for(const key of selection)o.module_status[key]=status;});};
$('find').onclick=()=>{if(!flushInput())return;try{layoutMode=false;canvasControls();selected=findLabel($('search').value);selection=new Set([L.info(scene,selected.c,selected.r).key]);$('viewport').focus({preventScroll:true});view.fitted=false;view.scale=Math.max(view.scale,Math.min(4,90/Math.min(project.module_width,project.module_height)));view.x=view.w/2-(activeItem().x+(selected.c+.5)*project.module_width)*view.scale;view.y=view.h/2-(activeItem().y+(selected.r+.5)*project.module_height)*view.scale;inspect();render();}catch(e){toast(e.message);}};
$('search').onkeydown=e=>{if(e.key==='Enter')$('find').click();};$('fit').onclick=fitAll;$('actual').onclick=()=>zoomAt(1/view.scale);$('zoomIn').onclick=()=>zoomAt(1.3);$('zoomOut').onclick=()=>zoomAt(1/1.3);$('undo').onclick=undo;$('redo').onclick=redo;
$('newProject').onclick=()=>{if(!valid&&!confirm('Discard invalid settings and start a new layout?'))return;open(L.clone(L.defaults));};
$('recent').onchange=()=>{const n=$('recent').value;if(n==='')return;const o=L.clone(recent[Number(n)].project);$('recentDialog').close();if(!valid&&!confirm('Discard invalid settings and open this project?'))return;open(o);};
$('openProject').onclick=()=>{importAsLayout=false;$('file').click();};$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8000000)throw Error('Project file exceeds 8 MB.');const o=L.normalize(JSON.parse(await f.text()));if(importAsLayout){importAsLayout=false;if(addLayout(o))toast('Added layout to canvas');return;}if(!valid&&!confirm('Discard invalid settings and open this project?'))return;await open(o);toast('Opened '+o.projectName);}catch(err){toast('Could not open project: '+err.message);}finally{importAsLayout=false;e.target.value='';}};
$('saveProject').onclick=saveProject;$('svg').onclick=()=>exportRun('svg',()=>download(filename('svg'),new Blob([L.svg(exportScene())],{type:'image/svg+xml'})));$('png').onclick=()=>exportRun('png',png);$('csv').onclick=()=>exportRun('csv',()=>download(filename('csv'),new Blob([L.csv(exportScene())],{type:'text/csv;charset=utf-8'})));
function pdf(details){return ()=>exportRun(details?'pdf':'pdfOverview',()=>{const p=LayoutPDF.plan(exportScene(),details);if(details&&p.minFont<5&&!confirm(`Detail labels will be ${p.minFont.toFixed(1)} pt. Reduce modules per page for larger text. Export anyway?`))return;download(filename(details?'pdf':'overview.pdf'),new Blob([LayoutPDF.build(exportScene(),details)],{type:'application/pdf'}));});}
$('pdf').onclick=pdf(true);$('pdfOverview').onclick=pdf(false);$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('dismissRecovery').onclick=()=>$('recovery').hidden=true;
$('quit').onclick=async()=>{if(!flushInput())return;try{clearTimeout(saveTimer);addRecent(project);await persist();if(hosted){await api('/api/quit',{});ready=false;document.body.innerHTML='<main style="height:100vh;justify-content:center;align-items:center"><h1>Your work is saved.</h1><p>You can close this window. Open the portable EXE to return.</p></main>';window.close();}else toast('Saved in this browser. You can close this tab.');}catch(e){toast('Could not save before closing: '+e.message);}};
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();}else if(!typing&&(e.ctrlKey||e.metaKey)){if(e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.key.toLowerCase()==='y'){e.preventDefault();redo();}}});
window.addEventListener('beforeunload',e=>{if(ready){flushInput();if(!valid){e.preventDefault();e.returnValue='';}}});
window.addEventListener('pagehide',()=>{if(ready){flushInput();if(valid&&hosted)fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json','X-Layout-Token':token},body:JSON.stringify(state()),keepalive:true}).catch(()=>{});}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready&&valid){flushInput();persist().catch(()=>{});}});
async function boot(){fill();refresh();buttons();initEffects();new ResizeObserver(resize).observe($('viewport'));try{const saved=hosted?await api('/api/state'):JSON.parse(localStorage.getItem('led-layout-mobile-v1')||'null');if(saved){recent=(Array.isArray(saved.recent)?saved.recent:[]).map(r=>{try{return {project:L.normalize(r.project),savedAt:r.savedAt};}catch(_){return null;}}).filter(Boolean).slice(0,5);updateRecent();if(saved.working){await open(saved.working,true);$('recovery').hidden=false;}}$('saveState').textContent=hosted?'Ready · saves to Projects':'Browser mode · save JSON backups';}catch(e){toast('Recovery could not be loaded: '+e.message);$('saveState').textContent='Recovery unavailable — save JSON backups';}ready=true;$('runtimeInfo').textContent=hosted?'This session saves projects to the Projects folder beside the portable EXE.':'Opened directly in a browser. Recovery uses browser storage; Save Project downloads JSON backups.';resize();fitAll();if(hosted)setInterval(()=>{if(ready)api('/api/ping').catch(()=>{$('saveState').textContent='Connection lost — reopen the portable EXE';});},20000);}

$('sectionCsv').onclick=()=>exportRun('sectionCsv',()=>download(filename('sections.csv'),new Blob([L.sectionCsv(exportScene())],{type:'text/csv;charset=utf-8'})));

function builderSummary(){try{const c=L.splitEven(Number($('totalWide').value),Number($('sectionCount').value)),r=L.splitEven(Number($('totalHigh').value),Number($('bandCount').value));$('builderSummary').textContent='Build preview — widths: '+L.compact(c)+' · Heights: '+L.compact(r);}catch(e){$('builderSummary').textContent=e.message;}}
['totalWide','totalHigh','sectionCount','bandCount'].forEach(id=>$(id).addEventListener('input',builderSummary));
$('applyLayout').onclick=()=>{try{const o=read();o.col_groups=L.splitEven(Number($('totalWide').value),Number($('sectionCount').value)).join(',');o.row_groups=L.splitEven(Number($('totalHigh').value),Number($('bandCount').value)).join(',');o.modules_wide=L.list(o.col_groups).reduce((a,b)=>a+b,0);commit(o,true);}catch(e){toast(e.message);}};
$('clearSelection').onclick=()=>{selected=null;selection.clear();inspect();render();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('helpDialog').open&&!$('sheetsDialog').open){selected=null;selection.clear();inspect();render();}});
$('xlsx').onclick=()=>exportRun('xlsx',()=>download(filename('xlsx'),new Blob([LayoutXLSX.build(exportScene())],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})));
if($('sheetsHelp'))$('sheetsHelp').onclick=()=>$('sheetsDialog').showModal();$('closeSheetsHelp').onclick=()=>$('sheetsDialog').close();

function selectModule(q,add=false,toggle=false){const key=L.info(scene,q.c,q.r).key;if(!add)selection.clear();if(add&&toggle&&selection.has(key)){selection.delete(key);selected=selection.size?L.locate(scene,[...selection].at(-1)):null;}else{selection.add(key);selected=q;}$('viewport').focus({preventScroll:true});inspect();render();}
function keepActiveVisible(){if(!selected)return;const mw=scene.o.module_width*view.scale,mh=scene.o.module_height*view.scale,x=view.x+activeItem().x*view.scale+selected.c*mw,y=view.y+activeItem().y*view.scale+selected.r*mh,pad=16;let dx=0,dy=0;if(x<pad)dx=pad-x;else if(x+mw>view.w-pad)dx=view.w-pad-x-mw;if(y<pad)dy=pad-y;else if(y+mh>view.h-pad)dy=view.h-pad-y-mh;if(dx||dy){view.fitted=false;view.x+=dx;view.y+=dy;render();}}
document.addEventListener('keydown',e=>{const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},d=moves[e.key],el=document.activeElement;if(!d||layoutMode||!selected||!valid||e.altKey||e.shiftKey||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(el.tagName)||el.isContentEditable||document.querySelector('dialog[open]'))return;e.preventDefault();const c=Math.max(0,Math.min(scene.cols-1,selected.c+d[0])),r=Math.max(0,Math.min(scene.rows-1,selected.r+d[1]));if(c===selected.c&&r===selected.r)return;selectModule({c,r},e.ctrlKey||e.metaKey);keepActiveVisible();});

function styleControls(){const test=L.isTest(scene),cabinet=L.isCabinet(scene)||test;$('testStyleOptions').hidden=!test;$('cabinetStyleOptions').hidden=!L.isCabinet(scene);$('classicStyleOptions').hidden=cabinet;$('blockLineLabel').hidden=cabinet;$('sections_per_alpha_block').disabled=cabinet;$('sectionCountLabel').textContent=cabinet?'Cabinets across':'Sections across';$('bandCountLabel').textContent=cabinet?'Cabinets high':'Bands high';$('layoutExplanation').textContent=cabinet?'Each cabinet contains modules. Set total modules and the number of cabinets, or switch styles on your existing layout.':'Set the overall size, then choose how many sections to divide it into.';$('search').placeholder='Label or address';$('sectionCsv').textContent=cabinet?'Cabinet counts CSV':'Section counts CSV';$('cabinetInspectorNote').hidden=!cabinet;$('sectionLineText').textContent=cabinet?'Cabinet line':'Section line';$('selectedWidthText').textContent=cabinet?'Cabinet width':'Section width';$('selectedHeightText').textContent=cabinet?'Cabinet height':'Band height';for(const id of ['selectedColor','setSectionColor','setLetterColor','clearSectionColor']){const e=$(id);(id==='selectedColor'?e.parentElement:e).hidden=cabinet;}}

let importAsLayout=false;
function activeItem(){return project.workspace.items.find(i=>i.id===project.workspace.activeId);}
function exportScene(){return $('exportScope').value==='active'?L.validate({...L.flat(scene.o),workspace:{effects:scene.o.workspace.effects,grid:scene.o.workspace.grid,activeId:activeItem().id,items:[{...activeItem(),layout:null,x:0,y:0}]}}):scene;}
function canvasControls(){const list=$('layoutList');list.replaceChildren();for(const i of project.workspace.items)list.add(new Option(i.name,i.id));list.value=project.workspace.activeId;const i=activeItem();$('positionLayoutName').textContent=i.name;$('moveCoordinates').hidden=!layoutMode;$('layoutName').value=i.name;$('layoutX').value=i.x;$('layoutY').value=i.y;$('removeLayout').disabled=project.workspace.items.length===1;$('layoutMode').classList.toggle('active',layoutMode);$('moduleMode').classList.toggle('active',!layoutMode);}
function activate(id){if(id===project.workspace.activeId)return true;selected=null;selection.clear();return commit(L.activateLayout(project,id),false,false);}
function addLayout(source){if(source?.workspace?.items.length>1){toast("Add JSON accepts a single layout. Use Open JSON to open a complete canvas.");return false;}if(!flushInput())return false;const o=L.clone(project),b=L.canvasBounds(scene);let n=1;while(o.workspace.items.some(i=>i.id==='layout'+n))n++;const id='layout'+n,layout=L.flat(source||L.validate({...L.clone(L.defaults),modules_wide:12,col_groups:'3x4',row_groups:'2x4',layout_style:project.layout_style}).o);o.workspace.items.push({id,name:'Layout '+n,x:Math.min(1000000,b.maxX+60),y:b.minY,layout});selected=null;selection.clear();try{return commit(L.validate(L.activateLayout(o,id)).o,true);}catch(e){toast(e.message);return false;}}
$('layoutList').onchange=()=>{const id=$('layoutList').value;if(flushInput())activate(id);};
$('addLayout').onclick=()=>addLayout();$('duplicateLayout').onclick=()=>{if(flushInput())addLayout(L.flat(project));};
$('importLayout').onclick=()=>{importAsLayout=true;$('file').click();};
$('renameLayout').onclick=()=>{const name=$('layoutName').value;mutate(o=>{o.workspace.items.find(i=>i.id===o.workspace.activeId).name=L.labelText(name);});};
for(const id of ['layoutX','layoutY'])$(id).onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('placeLayout').onclick();}};
$('placeLayout').onclick=()=>{const rawX=$('layoutX').value.trim(),rawY=$('layoutY').value.trim(),x=rawX===''?NaN:Number(rawX),y=rawY===''?NaN:Number(rawY);mutate(o=>{if(!Number.isSafeInteger(x)||!Number.isSafeInteger(y)||Math.abs(x)>1000000||Math.abs(y)>1000000)throw Error('Use whole-number positions between -1,000,000 and 1,000,000.');const i=o.workspace.items.find(i=>i.id===o.workspace.activeId);const point=L.Effects.snapLayout({x,y},i.id,L.canvasScenes(L.validate(o)),o.workspace.grid,10/view.scale);i.x=point.x;i.y=point.y;});};
$('removeLayout').onclick=()=>{if(!flushInput()||project.workspace.items.length===1)return;const id=project.workspace.activeId,nextId=project.workspace.items.find(i=>i.id!==id).id,o=L.activateLayout(project,nextId);o.workspace.items=o.workspace.items.filter(i=>i.id!==id);selected=null;selection.clear();commit(o,true);};
function layerOrder(front){mutate(o=>{const at=o.workspace.items.findIndex(i=>i.id===o.workspace.activeId),item=o.workspace.items.splice(at,1)[0];front?o.workspace.items.push(item):o.workspace.items.unshift(item);});}
$('frontLayout').onclick=()=>layerOrder(true);$('backLayout').onclick=()=>layerOrder(false);
$('layoutMode').onclick=()=>{if(!flushInput())return;layoutMode=true;selected=null;selection.clear();canvasControls();inspect();render();};
$('moduleMode').onclick=()=>{layoutMode=false;canvasControls();render();};
$('exportScope').onchange=summary;
function labelControls(i){const section=$('labelScope').value==='section';$('labelEditor').value=(section?project.section_labels[i.label]:project.module_labels[i.key])||'';$('labelEditor').placeholder=section?L.addressLabel(scene,i):i.lc+':'+i.lr;for(const id of ['labelEditor','labelScope','applyLabel','resetLabel'])$(id).disabled=selection.size!==1;}
$('labelScope').onchange=()=>{if(selected)labelControls(selectedInfo());};
$('applyLabel').onclick=()=>{const value=$('labelEditor').value,scope=$('labelScope').value;mutate(o=>{const i=selectedInfo();o[scope==='section'?'section_labels':'module_labels'][scope==='section'?i.label:i.key]=L.labelText(value);});};
$('resetLabel').onclick=()=>{const scope=$('labelScope').value;mutate(o=>{const i=selectedInfo();delete o[scope==='section'?'section_labels':'module_labels'][scope==='section'?i.label:i.key];});};

function settingsSummary(){const s=scene,o=s.o;$('setupSummary').textContent=`Layout: ${s.cols} × ${s.rows} · ${s.cg.length} across · ${s.rg.length} high`;$('appearanceSummary').textContent=`Appearance: ${L.isTest(s)?'Checkerboard':L.isCabinet(s)?'Novastar RGB':'MRI'} · ${o.module_width} × ${o.module_height} px`;$('exportSummary').textContent=`Export: ${$('exportScope').value==='active'?'Active layout':'Entire canvas'} · ${o.paper} ${o.landscape?'landscape':'portrait'}`;}
function showSettingsTab(name){for(const n of ['Setup','Appearance','Effects','Export']){const active=n===name;$('panel'+n).hidden=!active;$('tab'+n).setAttribute('aria-selected',String(active));$('tab'+n).tabIndex=active?0:-1;}}
for(const [index,name] of ['Setup','Appearance','Effects','Export'].entries()){const tab=$('tab'+name);tab.onclick=()=>showSettingsTab(name);tab.onkeydown=e=>{const names=['Setup','Appearance','Effects','Export'];let next=index;if(e.key==='ArrowRight')next=(index+1)%4;else if(e.key==='ArrowLeft')next=(index+3)%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();showSettingsTab(names[next]);$('tab'+names[next]).focus();};}
let previousFind='',findIndex=-1,findResults=[];
function findLabel(query){const q=query.trim().toLocaleLowerCase();if(!q)throw Error('Enter a label or address.');const all=L.canvasScenes(scene),ordered=[...all.filter(i=>i.id===project.workspace.activeId),...all.filter(i=>i.id!==project.workspace.activeId)];let results=ordered.flatMap(i=>L.searchLabels(i.scene,query).map(pos=>({id:i.id,...pos})));if(!results.length)throw Error('No matching label or address.');const signature=JSON.stringify(results.slice().sort((a,b)=>a.id.localeCompare(b.id)||a.r-b.r||a.c-b.c));if(previousFind===q+'|'+signature){findIndex=(findIndex+1)%findResults.length;}else{previousFind=q+'|'+signature;findResults=results;findIndex=0;}const hit=findResults[findIndex];if(hit.id!==project.workspace.activeId)activate(hit.id);if(findResults.length>1)toast(`Match ${findIndex+1} of ${findResults.length} · ${activeItem().name}`);return {c:hit.c,r:hit.r};}
function closeFileMenu(focus=false){$('fileMenu').hidden=true;$('fileMenuButton').setAttribute('aria-expanded','false');if(focus)$('fileMenuButton').focus();}
function fileMenuItems(){return [...document.querySelectorAll('#fileMenu button')].filter(e=>!e.disabled);}
$('fileMenuButton').onclick=()=>{const open=$('fileMenu').hidden;$('fileMenu').hidden=!open;$('fileMenuButton').setAttribute('aria-expanded',String(open));if(open)fileMenuItems()[0]?.focus();};
$('fileMenuButton').onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();$('fileMenu').hidden=false;$('fileMenuButton').setAttribute('aria-expanded','true');fileMenuItems()[0]?.focus();}};
$('fileMenu').addEventListener('click',e=>{if(e.target.closest('button'))closeFileMenu();});
$('fileMenu').onkeydown=e=>{const items=fileMenuItems(),index=items.indexOf(document.activeElement);let next;if(e.key==='ArrowDown')next=(index+1)%items.length;else if(e.key==='ArrowUp')next=(index-1+items.length)%items.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=items.length-1;else if(e.key==='Escape'){e.preventDefault();closeFileMenu(true);return;}else if(e.key==='Tab'){closeFileMenu();return;}else return;e.preventDefault();items[next]?.focus();};
document.addEventListener('click',e=>{if(!e.target.closest('.fileMenu'))closeFileMenu();});
$('projectProperties').onclick=()=>{$('propertiesDialog').showModal();$('projectName').focus();};
$('closeProperties').onclick=()=>{if(flushInput())$('propertiesDialog').close();};
$('recentProjects').onclick=()=>$('recentDialog').showModal();$('closeRecent').onclick=()=>$('recentDialog').close();$('fileQuit').onclick=()=>$('quit').click();
$('about').onclick=()=>{$('aboutVersion').textContent='Version '+L.defaults.version;$('aboutDialog').showModal();};$('closeAbout').onclick=()=>$('aboutDialog').close();
$('resetCabinetColors').onclick=()=>mutate(o=>{for(const key of ["cabinet_dark1","cabinet_dark2","cabinet_dark3","cabinet_light1","cabinet_light2","cabinet_light3","cabinet_text","cabinet_grid"])o[key]=L.defaults[key];});
$('resetTestColors').onclick=()=>mutate(o=>{for(const key of ["test_color1","test_color2","test_line","test_text","test_badge"])o[key]=L.defaults[key];});
const effectInputs=[...document.querySelectorAll('[data-effect]')],gridInputs=[...document.querySelectorAll('[data-canvas-grid]')];
let effectRuntime=null,recordingAbort=null;
function fillWorkspaceControls(){for(const e of effectInputs){const value=project.workspace.effects[e.dataset.effect];if(e.type==='checkbox')e.checked=value;else e.value=value;}for(const e of gridInputs){const value=project.workspace.grid[e.dataset.canvasGrid];if(e.type==='checkbox')e.checked=value;else e.value=value;}}
function readWorkspaceControls(o){for(const e of effectInputs)o.workspace.effects[e.dataset.effect]=e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value;for(const e of gridInputs)o.workspace.grid[e.dataset.canvasGrid]=e.type==='checkbox'?e.checked:Number(e.value);}
for(const e of [...effectInputs,...gridInputs]){e.addEventListener('input',inputChanged);e.addEventListener('change',()=>{clearTimeout(inputTimer);commit(read());});}
function drawCanvasGrid(){const g=scene.o.workspace.grid,plan=L.Effects.gridPlan(g,view);$('gridDisplay').textContent=plan&&plan.multiplier>1?'Display every '+plan.multiplier+' grid lines':'';if(!plan)return;ctx.save();ctx.lineWidth=1;ctx.strokeStyle='#253442';ctx.beginPath();for(let x=plan.left;x<=plan.right;x+=plan.step){const px=view.x+x*view.scale;ctx.moveTo(px,0);ctx.lineTo(px,view.h);}for(let y=plan.top;y<=plan.bottom;y+=plan.step){const py=view.y+y*view.scale;ctx.moveTo(0,py);ctx.lineTo(view.w,py);}ctx.stroke();ctx.strokeStyle='#516879';ctx.beginPath();if(view.x>=0&&view.x<=view.w){ctx.moveTo(view.x,0);ctx.lineTo(view.x,view.h);}if(view.y>=0&&view.y<=view.h){ctx.moveTo(0,view.y);ctx.lineTo(view.w,view.y);}ctx.stroke();ctx.restore();}
function initEffects(){effectRuntime={canvas:$('effectsCanvas'),ctx:$('effectsCanvas').getContext('2d'),request:0,time:0,last:performance.now(),paused:false,bounds:null,stamp:0};const f=LayoutVideo.format();$('videoFormat').textContent=f?'Format: '+f.ext.toUpperCase()+' · 30 fps':'Video recording unavailable in this browser';$('exportVideo').disabled=!f;syncEffects();document.addEventListener('visibilitychange',()=>{effectRuntime.last=performance.now();syncEffects();});}
function syncEffects(){if(!effectRuntime)return;const e=scene.o.workspace.effects;$('pauseEffects').textContent=effectRuntime.paused?'Play':'Pause';$('pauseEffects').disabled=!e.enabled;$('restartEffects').disabled=!e.enabled;$('effectStatus').textContent=!e.enabled?'Effects off':effectRuntime.paused?'Paused':'Playing · '+e.cycle+' second cycle';for(const input of effectInputs)if(input.dataset.effect!=='enabled')input.disabled=!e.enabled;$('fx_direction').disabled=!e.enabled||!['wave','cross'].includes(e.mode);for(const key of ['pulseStyle','count'])$('fx_'+key).disabled=!e.enabled||e.mode!=='pulse';for(const key of ['fill','trail'])$('fx_'+key).disabled=!e.enabled||(e.mode==='pulse'&&e.pulseStyle==='ring');effectRuntime.last=performance.now();if(effectRuntime.request){cancelAnimationFrame(effectRuntime.request);effectRuntime.request=0;}refreshEffectsFrame();queueEffects();}
function refreshEffectsFrame(){if(!effectRuntime)return;const r=effectRuntime,dpr=window.devicePixelRatio||1;r.bounds=L.canvasBounds(scene);if(r.canvas.width!==canvas.width||r.canvas.height!==canvas.height){r.canvas.width=canvas.width;r.canvas.height=canvas.height;}drawEffectsFrame(dpr);}
function drawEffectsFrame(dpr=window.devicePixelRatio||1){const r=effectRuntime;if(!r)return;const c=r.ctx;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,r.canvas.width,r.canvas.height);if(!valid||!scene.o.workspace.effects.enabled||!r.bounds)return;c.setTransform(dpr*view.scale,0,0,dpr*view.scale,dpr*view.x,dpr*view.y);L.Effects.draw(c,r.bounds,scene.o.workspace.effects,r.time,view.scale);}
function queueEffects(){const r=effectRuntime;if(!r||r.request||r.paused||document.hidden||!valid||!scene.o.workspace.effects.enabled)return;r.request=requestAnimationFrame(now=>{r.request=0;if(now-r.stamp>=1000/30){r.time+=Math.max(0,Math.min(1,(now-r.last)/1000));r.last=now;r.stamp=now;drawEffectsFrame();}queueEffects();});}
$('pauseEffects').onclick=()=>{if(!flushInput())return;effectRuntime.paused=!effectRuntime.paused;syncEffects();};$('restartEffects').onclick=()=>{if(!flushInput())return;effectRuntime.time=0;effectRuntime.paused=false;syncEffects();};
$('cancelVideo').onclick=()=>recordingAbort?.abort();$('recordDialog').addEventListener('cancel',e=>{e.preventDefault();recordingAbort?.abort();});
$('exportVideo').onclick=async()=>{
 if(recordingAbort||!flushInput())return;const duration=Number($('videoDuration').value),max=Number($('videoSize').value);if(!Number.isFinite(duration)||duration<1||duration>60){toast('Video duration must be from 1 to 60 seconds.');return;}
 const format=LayoutVideo.format();if(!format){toast('Video recording is unavailable in this browser.');return;}const snapshot=L.validate(L.clone(exportScene().o)),bounds=L.canvasBounds(snapshot),dims=LayoutVideo.dimensions(bounds.W,bounds.H,max);const c=document.createElement('canvas');c.width=dims.width;c.height=dims.height;const cx=c.getContext('2d');let url=null;recordingAbort=new AbortController();$('recordProgress').textContent='Preparing '+format.ext.toUpperCase()+' · '+dims.width+' × '+dims.height;$('recordMeter').value=0;$('recordDialog').showModal();
 try{
  const svg=L.svg(snapshot).replace(/(<svg\b[^>]*\bwidth=")[^"]+/,(_,a)=>a+dims.width).replace(/(<svg\b[^>]*\bheight=")[^"]+/,(_,a)=>a+dims.height);url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Could not render the video background.'));img.src=url;});
  const result=await LayoutVideo.record(c,time=>{cx.setTransform(1,0,0,1,0,0);cx.clearRect(0,0,c.width,c.height);cx.drawImage(img,0,0,c.width,c.height);const scaleX=c.width/bounds.W,scaleY=c.height/bounds.H;cx.setTransform(scaleX,0,0,scaleY,-bounds.minX*scaleX,-bounds.minY*scaleY);L.Effects.draw(cx,bounds,snapshot.o.workspace.effects,time,Math.min(scaleX,scaleY));},duration,progress=>{$('recordMeter').value=progress*100;$('recordProgress').textContent='Recording '+format.ext.toUpperCase()+' · '+Math.round(progress*100)+'%';},recordingAbort.signal);
  download(filename(result.ext),result.blob);toast(result.ext.toUpperCase()+' video exported.');
 }catch(e){toast(e.message);}finally{if(url)URL.revokeObjectURL(url);c.width=c.height=1;recordingAbort=null;$('recordDialog').close();}
};
boot();
