(function(root){
'use strict';const L=root.Layout||(typeof require!=='undefined'?require('./core.js'):null),N=n=>Number(n.toFixed(4)).toString(),esc=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/[\\()]/g,'\\$&'),color=h=>[1,3,5].map(i=>N(parseInt(h.slice(i,i+2),16)/255)).join(' ');
function plan(s,details){const sizes={A4:[210,297],A3:[297,420],Letter:[215.9,279.4],Tabloid:[279.4,431.8]},size=sizes[s.o.paper].map(n=>n*72/25.4);if(s.o.landscape)size.reverse();const [w,h]=size,margin=s.o.margin*72/25.4,areaW=w-margin*2,areaH=h-margin*2-70,b=L.canvasBounds(s),mw=s.o.module_width,mh=s.o.module_height,tw=s.o.tile_cols*mw,th=s.o.tile_rows*mh,pages=[{wx:0,wy:0,pw:b.W,ph:b.H,overview:true}];if(details){if(Math.ceil(b.W/tw)*Math.ceil(b.H/th)>500)throw Error('This canvas would create more than 500 detail pages. Increase modules per page or move layouts closer together.');for(let y=0;y<b.H;y+=th)for(let x=0;x<b.W;x+=tw)pages.push({wx:x,wy:y,pw:Math.min(tw,b.W-x),ph:Math.min(th,b.H-y),overview:false});}let minFont=Infinity;for(const pg of pages){pg.c=pg.wx/mw;pg.r=pg.wy/mh;pg.cols=pg.pw/mw;pg.rows=pg.ph/mh;pg.scale=Math.min(areaW/(pg.overview?b.W:Math.min(tw,b.W)),areaH/(pg.overview?b.H:Math.min(th,b.H)));pg.x=pg.overview?margin+(areaW-pg.pw*pg.scale)/2:margin;pg.y=pg.overview?margin+45+(areaH-pg.ph*pg.scale)/2:margin+45;if(!pg.overview)for(const item of b.items){const child=item.scene,clip={c:(pg.wx-item.x+b.minX)/child.o.module_width,r:(pg.wy-item.y+b.minY)/child.o.module_height,cols:pg.pw/child.o.module_width,rows:pg.ph/child.o.module_height};if(clip.c>=child.cols||clip.r>=child.rows||clip.c+clip.cols<=0||clip.r+clip.rows<=0)continue;let font=L.isCabinet(child)?L.cabinetLabels(child,clip).reduce((a,t)=>Math.min(a,t.fs),Infinity):L.typography(child).fs;for(const value of [...Object.values(child.o.module_labels),...Object.values(child.o.section_labels)])font=Math.min(font,child.o.module_width*.86/(value.length*.6));minFont=Math.min(minFont,font*pg.scale);}}return {w,h,margin,pages,minFont,bounds:b};}
function build(s,details=true){const p=plan(s,details),o=s.o,objects=[null,'',''],streams=[],date=new Date().toISOString().slice(0,10),multi=p.bounds.items.length>1;
 for(let pageNo=0;pageNo<p.pages.length;pageNo++){
 const pg=p.pages[pageNo],a=[],text=(x,y,size,t,fill='#111827',center=false,outline=false)=>{if(outline)a.push('q',`0.149 0.1961 0.2196 RG ${N(size*.07)} w 1 j 2 Tr`);a.push(`${color(fill)} rg BT /F1 ${N(size)} Tf 1 0 0 1 ${N(x-(center?String(t).length*size*.3:0))} ${N(p.h-y)} Tm (${esc(t)}) Tj ET`);if(outline){a.push('Q');text(x,y,size,t,fill,center,false);}},rect=(x,y,w,h,fill)=>a.push(`${color(fill)} rg ${N(x)} ${N(p.h-y-h)} ${N(w)} ${N(h)} re f`),line=(x1,y1,x2,y2,width,fill)=>{if(width)a.push(`${color(fill)} RG ${N(width)} w ${N(x1)} ${N(p.h-y1)} m ${N(x2)} ${N(p.h-y2)} l S`);};
 const title=o.projectName+' | Rev '+o.revision;text(p.margin,p.margin+11,Math.min(13,(p.w-2*p.margin)/(Math.max(1,title.length)*.6)),title);text(p.margin,p.margin+27,8,(multi?p.bounds.items.length+' layouts | '+p.bounds.W+' x '+p.bounds.H+' px canvas':o.horizontal_view+' / '+o.vertical_order+' | '+s.cols+' x '+s.rows+' modules')+' | '+date);
 const caption=pg.overview?'OVERVIEW':multi?`DETAIL | Canvas x ${pg.wx+p.bounds.minX}, y ${pg.wy+p.bounds.minY} px`:`DETAIL | Display columns ${pg.c+1}-${pg.c+pg.cols}, rows ${pg.r+1}-${pg.r+pg.rows}`;text(p.margin,p.margin+40,8,caption);
 a.push('q',`${N(pg.x)} ${N(p.h-pg.y-pg.ph*pg.scale)} ${N(pg.pw*pg.scale)} ${N(pg.ph*pg.scale)} re W n`);
 for(const item of p.bounds.items){const child=item.scene,co=child.o,mw=co.module_width,mh=co.module_height,dx=item.x-p.bounds.minX,dy=item.y-p.bounds.minY;if(dx>=pg.wx+pg.pw||dy>=pg.wy+pg.ph||dx+child.W<=pg.wx||dy+child.H<=pg.wy)continue;const x=v=>pg.x+(v+dx-pg.wx)*pg.scale,y=v=>pg.y+(v+dy-pg.wy)*pg.scale,clip={c:Math.max(0,(pg.wx-dx)/mw),r:Math.max(0,(pg.wy-dy)/mh)};clip.cols=Math.min(child.cols,(pg.wx+pg.pw-dx)/mw)-clip.c;clip.rows=Math.min(child.rows,(pg.wy+pg.ph-dy)/mh)-clip.r;const rs=L.rects(child),{off}=L.typography(child);
 a.push('q',`${N(x(0))} ${N(p.h-y(child.H))} ${N(child.W*pg.scale)} ${N(child.H*pg.scale)} re W n`);
 for(const q of rs)rect(x(q.x*mw),y(q.y*mh),q.w*mw*pg.scale,q.h*mh*pg.scale,q.fill);
 for(const q of L.highlights(child))rect(x(q.x*mw),y(q.y*mh),mw*pg.scale,mh*pg.scale,q.fill);
 L.grid(child,(x1,y1,x2,y2,width)=>line(x(x1),y(y1),x(x2),y(y2),width*pg.scale,L.palette(child).grid));
 if(!L.isCabinet(child)&&!L.isTest(child)&&co.show_labels)for(let r=Math.floor(clip.r);r<Math.ceil(clip.r+clip.rows);r++)for(let c=Math.floor(clip.c);c<Math.ceil(clip.c+clip.cols);c++){const i=L.info(child,c,r),fs=L.moduleFont(child,i),cx=(c+.5)*mw,cy=(r+.5)*mh;text(x(cx),y(cy-off+fs*.3),fs*pg.scale,L.displayLabel(child,i),co.text_color,true);text(x(cx),y(cy+off+fs*.3),fs*pg.scale,L.moduleText(child,i),co.text_color,true);}
 if(!L.isCabinet(child)&&!L.isTest(child)&&co.show_headings)for(const q of rs){const f=Math.min(Math.min(mw,mh)*.15,q.w*mw/(q.displayLabel.length*.6+1.4)),pad=Math.min(mw,mh)*.02;rect(x(q.x*mw+pad),y(q.y*mh+pad),(q.displayLabel.length*.6+1)*f*pg.scale,f*1.3*pg.scale,'#FFFFFF');text(x(q.x*mw+pad+f*.4),y(q.y*mh+pad+f),f*pg.scale,q.displayLabel);}
 if(L.isCabinet(child)&&co.show_cabinet_labels)for(const t of L.cabinetLabels(child,clip))text(x(t.x),y(t.y+t.fs*.3),t.fs*pg.scale,t.text,L.palette(child).text,true,true);
 if(L.isCabinet(child))for(const t of L.moduleLabelPositions(child))text(x(t.x),y(t.y),t.fs*pg.scale,t.text,L.palette(child).text,true,true);
 if(L.isTest(child))for(const shape of L.testGeometry(child,item.name)){if(shape.type==='line')line(x(shape.x1),y(shape.y1),x(shape.x2),y(shape.y2),shape.width*pg.scale,shape.color);else if(shape.type==='rect')rect(x(shape.x),y(shape.y),shape.w*pg.scale,shape.h*pg.scale,shape.color);else text(x(shape.x),y(shape.y),shape.fs*pg.scale,shape.text,shape.color,true);}
 a.push('Q');}
 a.push('Q');text(p.margin,p.h-p.margin-11,7,multi?'Layouts keep canvas positions and stacking order':`${L.isCabinet(s)?L.cabinetId(s,0,0):'A1'} origin: ${o.vertical_order==='Top to Bottom'?'top':'bottom'}-${o.horizontal_view==='Rear'?'left':'right'}`);text(p.margin,p.h-p.margin,7,`Page ${pageNo+1} of ${p.pages.length} | LED Layout Generator 3.15`);streams.push(a.join('\n')+'\n');}
 const fontId=3,firstPage=4;objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Kids [${p.pages.map((_,i)=>(firstPage+i*2)+' 0 R').join(' ')}] /Count ${p.pages.length} >>`;objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold >>';
 streams.forEach((stream,i)=>{const id=firstPage+i*2;objects[id]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${N(p.w)} ${N(p.h)}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${id+1} 0 R >>`;objects[id+1]=`<< /Length ${stream.length} >>\nstream\n${stream}endstream`;});
 let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return new Uint8Array(Array.from(pdf,c=>c.charCodeAt(0)));
}
const API={plan,build};root.LayoutPDF=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
