// Offline XLSX exporter. No installation, network requests or macros.
(function(root){'use strict';
const L=root.Layout||(typeof require!=='undefined'?require('./core.js'):null),enc=new TextEncoder();
const xml=v=>String(v).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function column(i){let a='';for(;i>0;i=Math.floor((i-1)/26))a=String.fromCharCode(65+(i-1)%26)+a;return a;}
const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xEDB88320^(n>>>1):n>>>1;return n>>>0;});
function crc(bytes){let n=0xFFFFFFFF;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return (n^0xFFFFFFFF)>>>0;}
function zip(files){const chunks=[],central=[];let offset=0;const pack=(size,fn)=>{const a=new Uint8Array(size);fn(new DataView(a.buffer));return a;};for(const [name,text] of Object.entries(files)){const path=enc.encode(name),data=enc.encode(text),sum=crc(data);const h=pack(30,d=>{d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x800,true);d.setUint16(12,33,true);d.setUint32(14,sum,true);d.setUint32(18,data.length,true);d.setUint32(22,data.length,true);d.setUint16(26,path.length,true);});const c=pack(46,d=>{d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,33,true);d.setUint32(16,sum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,path.length,true);d.setUint32(42,offset,true);});chunks.push(h,path,data);central.push(c,path);offset+=h.length+path.length+data.length;}const centralSize=central.reduce((a,b)=>a+b.length,0),end=pack(22,d=>{d.setUint32(0,0x06054b50,true);d.setUint16(8,central.length/2,true);d.setUint16(10,central.length/2,true);d.setUint32(12,centralSize,true);d.setUint32(16,offset,true);});const result=new Uint8Array(offset+centralSize+22);let at=0;for(const part of [...chunks,...central,end]){result.set(part,at);at+=part.length;}return result;}
function files(s){const o=s.o,ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',fills=['<fill><patternFill patternType="none"/></fill>','<fill><patternFill patternType="gray125"/></fill>','<fill><patternFill patternType="solid"><fgColor rgb="FF223344"/><bgColor indexed="64"/></patternFill></fill>'],borders=['<border><left/><right/><top/><bottom/><diagonal/></border>'],styles=[{font:0,fill:0,border:0},{font:2,fill:2,border:0},{font:3,fill:0,border:0},{font:0,fill:0,border:0,text:true}],fillIds=new Map(),borderIds=new Map(),styleIds=new Map();
 const cell=(ref,value,style=0,formula=null)=>`<c r="${ref}" s="${style}"${typeof value==='number'?'':' t="inlineStr"'}>${formula?`<f>${xml(formula)}</f>`:''}${typeof value==='number'?`<v>${value}</v>`:`<is><t xml:space="preserve">${xml(value)}</t></is>`}</c>`;
 const lineStyle=w=>w<=0?'':w<=1?'thin':w<=3?'medium':'thick',vx=new Map(),hy=new Map();L.grid(s,(x1,y1,x2,y2,w)=>{if(x1===x2)vx.set(Math.round(x1/o.module_width),Math.max(vx.get(Math.round(x1/o.module_width))||0,w));else hy.set(Math.round(y1/o.module_height),Math.max(hy.get(Math.round(y1/o.module_height))||0,w));});
 function style(fill,c,r){if(!fillIds.has(fill)){fillIds.set(fill,fills.length);fills.push(`<fill><patternFill patternType="solid"><fgColor rgb="FF${fill.slice(1)}"/><bgColor indexed="64"/></patternFill></fill>`);}const sides=[vx.get(c),vx.get(c+1),hy.get(r),hy.get(r+1)].map(lineStyle),bk=sides.join(',');if(!borderIds.has(bk)){borderIds.set(bk,borders.length);borders.push('<border>'+['left','right','top','bottom'].map((v,i)=>sides[i]?`<${v} style="${sides[i]}"><color rgb="FF${L.palette(s).grid.slice(1)}"/></${v}>`:`<${v}/>`).join('')+'<diagonal/></border>');}const key=fill+'|'+bk;if(!styleIds.has(key)){if(styles.length>60000)throw Error('Too many unique styles for Excel. Reduce custom section colors.');styleIds.set(key,styles.length);styles.push({font:1,fill:fillIds.get(fill),border:borderIds.get(bk),module:true});}return styleIds.get(key);}
 const sheet=(rows,cols,freeze,merge='',filter='')=>`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane xSplit="${freeze?1:0}" ySplit="4" topLeftCell="${freeze?'B':'A'}5" activePane="${freeze?'bottomRight':'bottomLeft'}" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/>${cols}<sheetData>${rows}</sheetData>${filter?`<autoFilter ref="${filter}"/>`:''}${merge?`<mergeCells count="3">${[1,2,3].map(n=>`<mergeCell ref="A${n}:${merge}${n}"/>`).join('')}</mergeCells>`:''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>`;
 function metadata(note){return `<row r="1" ht="28" customHeight="1">${cell('A1',o.projectName+' — Rev '+o.revision,2)}</row><row r="2">${cell('A2',`${o.horizontal_view} / ${o.vertical_order} · ${s.cols} × ${s.rows} modules`)}</row><row r="3" ht="30" customHeight="1">${cell('A3',note||(L.isCabinet(s)?'One editable cell per module; cabinet ID / local column:row. Edits do not sync to app.':'Editable export. Changes here do not update the app or other tabs.'))}</row>`;}
 const colors=new Map(L.rects(s).map(q=>[q.label,q.fill]));let rows=metadata(),header=cell('A4','Row',1);for(let c=0;c<s.cols;c++)header+=cell(column(c+2)+'4',c+1,1);rows+=`<row r="4">${header}</row>`;
 const scale=40/Math.min(o.module_width,o.module_height),width=Math.min(255,Math.max(4,(o.module_width*scale-5)/7)),height=Math.min(409,Math.max(30,o.module_height*scale*.75));
 for(let r=0;r<s.rows;r++){let cells=cell('A'+(r+5),r+1,1);for(let c=0;c<s.cols;c++){const i=L.info(s,c,r);cells+=cell(column(c+2)+(r+5),L.displayLabel(s,i)+'\n'+L.moduleText(s,i),style(o.module_colors[i.key]||colors.get(i.label),c,r));}rows+=`<row r="${r+5}" ht="${height}" customHeight="1">${cells}</row>`;}
 const layout=sheet(rows,`<cols><col min="1" max="1" width="6" customWidth="1"/><col min="2" max="${s.cols+1}" width="${width}" customWidth="1"/></cols>`,true,column(Math.max(2,Math.min(s.cols+1,12))));
 function dataSheet(data,sections){let body=metadata(L.isCabinet(s)?'Cabinet IDs are row + column. Edits here do not update the app or other tabs.':null);data.forEach((row,ri)=>{body+=`<row r="${ri+4}">${row.map((v,ci)=>cell(column(ci+1)+(ri+4),v,ri===0?1:L.isCabinet(s)&&ci===0?3:0,sections&&ri>0&&ci===4?`C${ri+4}*D${ri+4}`:null)).join('')}</row>`;});if(sections){const n=data.length+4;body+=`<row r="${n}">${cell('D'+n,'Total',1)}${cell('E'+n,s.cols*s.rows,0,`SUM(E5:E${n-1})`)}</row>`;}return sheet(body,`<cols>${data[0].map((_,i)=>`<col min="${i+1}" max="${i+1}" width="${sections?20:i===3?24:18}" customWidth="1"/>`).join('')}</cols>`,false,column(data[0].length),`A4:${column(data[0].length)}${data.length+3}`);}
 const modules=dataSheet(L.moduleRows(s),false),sections=dataSheet(L.sectionRows(s),true);
 const styleXml=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${ns}"><fonts count="4"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="9"/><color rgb="FF${L.palette(s).text.slice(1)}"/><name val="Courier New"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font><font><b/><sz val="16"/><name val="Calibri"/></font></fonts><fills count="${fills.length}">${fills.join('')}</fills><borders count="${borders.length}">${borders.join('')}</borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${styles.length}">${styles.map(v=>`<xf numFmtId="${v.text?49:0}" applyNumberFormat="1" fontId="${v.font}" fillId="${v.fill}" borderId="${v.border}" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"${v.module?' horizontal="center"':''}/></xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';return {'[Content_Types].xml':`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${[1,2,3].map(i=>`<Override PartName="/xl/worksheets/sheet${i}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`,'_rels/.rels':`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`,'xl/workbook.xml':`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView activeTab="0"/></bookViews><sheets>${['Layout','Modules',L.isCabinet(s)?'Cabinets':'Sections'].map((name,i)=>`<sheet name="${name}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`,'xl/_rels/workbook.xml.rels':`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${[1,2,3].map(i=>`<Relationship Id="rId${i}" Type="${rel}/worksheet" Target="worksheets/sheet${i}.xml"/>`).join('')}<Relationship Id="rId4" Type="${rel}/styles" Target="styles.xml"/></Relationships>`,'xl/styles.xml':styleXml,'xl/worksheets/sheet1.xml':layout,'xl/worksheets/sheet2.xml':modules,'xl/worksheets/sheet3.xml':sections};
}

function canvasFiles(s){const base=files(s),ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',cell=(r,v,style=0,formula='')=>`<c r="${r}" s="${style}"${typeof v==='number'?'':' t="inlineStr"'}>${formula?'<f>'+xml(formula)+'</f>':''}${typeof v==='number'?'<v>'+v+'</v>':'<is><t xml:space="preserve">'+xml(v)+'</t></is>'}</c>`;
 const make=(data,quantity=false)=>`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" state="frozen"/></sheetView></sheetViews><cols>${data[0].map((_,i)=>'<col min="'+(i+1)+'" max="'+(i+1)+'" width="24" customWidth="1"/>').join('')}</cols><sheetData>${data.map((row,ri)=>'<row r="'+(ri+1)+'">'+row.map((v,ci)=>cell(column(ci+1)+(ri+1),v,ri===0?1:typeof v==='string'?3:0,quantity&&ri>0&&ci===4?'C'+(ri+1)+'*D'+(ri+1):'')).join('')+'</row>').join('')}</sheetData><autoFilter ref="A1:${column(data[0].length)}${data.length}"/></worksheet>`;
 const layouts=[['Layout','X (px)','Y (px)','Width (px)','Height (px)','Style','Stack order (back to front)'],...L.canvasScenes(s).map((i,index)=>[i.name,i.x,i.y,i.scene.W,i.scene.H,i.scene.o.layout_style,index+1])];
 base['xl/worksheets/sheet1.xml']=make(layouts);base['xl/worksheets/sheet2.xml']=make(L.canvasModuleRows(s));base['xl/worksheets/sheet3.xml']=make(L.canvasSectionRows(s),true);
 base['xl/workbook.xml']=base['xl/workbook.xml'].replace(/name="Layout"/,'name="Layouts"').replace(/name="Cabinets"/,'name="Sections"');return base;
}
function build(s){return zip(s.o.workspace?.items.length>1?canvasFiles(s):files(s));}
const API={build};root.LayoutXLSX=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
